---
- hosts: all
  user: vagrant
  sudo: yes
  tasks:

    - name: install epel
      action: command creates=/etc/yum.repos.d/epel.repo rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

    - name: make sure packages are installed
      action: yum pkg={{item}} state=installed
      with_items:
        - gdal
        - gdal-python
        - wgrib2

# gdal is needed to transform the data
# gdal-python bindings are used by the gdal2tiles.py
# wgrib2 is useful to see what is in the grib file

